<a href="https://colab.research.google.com/github/Mytros/DS_ML_homework/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_Dmytro_Koval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np
import random


# 1.1 np.random.rand
vector = np.random.rand(10)

# Створення матриці 3x3
A = np.array([
    [11, 20, 29],
    [14, 23, 32],
    [17, 26, 35]
])

print("Random vector:\n", vector_rand)
print("Random vector shape:", vector_rand.shape)

print("Matrix:\n", A)
print("Matrix shape:", A.shape)


Random vector:
 [0.65415616 0.83103125 0.28368971 0.68517274 0.40469    0.55264197
 0.29211902 0.32331341 0.83064029 0.50047033]
Random vector shape: (10,)
Matrix:
 [[11 20 29]
 [14 23 32]
 [17 26 35]]
Matrix shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
# 2.1
vector_plus_10 = np.round(vector + 10, 2)
print("2.1. Vector + 10 (round 2 digits):", vector_plus_10, "\n")

# 2.2
matrix_multiplied = matrix * 2
print("2.2. Matrix * 2:\n", matrix_multiplied,"\n")

# 2.3
vector_squared = vector ** 2
print("2.3. Vector squared:\n", vector_squared)

2.1. Vector + 10 (round 2 digits): [10.71 10.57 10.14 10.84 10.07 10.66 10.39 10.91 10.58 10.66] 

2.2. Matrix * 2:
 [[22 40 58]
 [28 46 64]
 [34 52 70]] 

2.3. Vector squared:
 [0.50767632 0.3276435  0.01934101 0.71345702 0.00483594 0.43162701
 0.15117615 0.83289569 0.33164784 0.4305054 ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [ ]:
# 3.1
result_matrix = np.dot(B, A)
print("result_matrix (B @ A):\n", result_matrix)
print("shape result_matrix:", result_matrix.shape)


result_matrix (B @ A):
 [[0.7281 0.5202]
 [0.2034 0.2846]]
shape result_matrix: (2, 2)


In [ ]:
# 3.2
result_vector = np.dot(result_matrix, C)
print("\n Result_vector:\n", result_vector)
print("Shape result_vector:", result_vector.shape)


 Result_vector:
 [[0.5202]
 [0.2846]]
Shape result_vector: (2, 1)


In [ ]:
# 3.3
result_D = np.dot(result_matrix, D)
print("\n Result_matrix:\n", result_D)
print("Shape result_matrix:", result_D.shape)


 Result_matrix:
 [[0.5202 0.7281]
 [0.2846 0.2034]]
Shape result_matrix: (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
# 4.1
result_matrix_T = result_matrix.T
print("Result_matrix transposed:\n", result_matrix_T)
print("Shape:", result_matrix_T.shape)


Result_matrix transposed:
 [[0.7281 0.2034]
 [0.5202 0.2846]]
Shape: (2, 2)


In [ ]:
# 4.2
vector_T = vector.T
print("Vector.shape:", vector.shape)
print("Vector transposed.shape:", vector_T.shape)


Vector.shape: (10,)
Vector transposed.shape: (10,)


Так як це 1-вимірний "масив", то транспонування нічого не змінює.

In [ ]:
# 4.3
column_vector = np.expand_dims(vector, axis=1)
print("Column_vector:\n", column_vector)
print("Shape column_vector:", column_vector.shape)


Column_vector:
 [[0.71251408]
 [0.57240152]
 [0.13907196]
 [0.84466385]
 [0.0695409 ]
 [0.65698327]
 [0.38881377]
 [0.91263119]
 [0.57588874]
 [0.6561291 ]]
Shape column_vector: (10, 1)


Column_vector тепер повноцінний вектор-стовбець, тобто повноцінна матриця у порівнянні з vector.


In [ ]:
# 4.4
column_vector_T = column_vector.T
print("Transposed column_vector:\n", column_vector_T)
print("Shape:", column_vector_T.shape)


Transposed column_vector:
 [[0.71251408 0.57240152 0.13907196 0.84466385 0.0695409  0.65698327
  0.38881377 0.91263119 0.57588874 0.6561291 ]]
Shape: (1, 10)


Column_vector можна транспонувати на відміну від vector.